// Programmatic pixel art. Each sprite is a palette + grid of single chars.
// Sprites for ground obstacles MUST have their visible content flush with
// the bottom row so origin (0.5, 1) anchors correctly.

const PAL = {
  s: '#f5c089', S: '#d99363', h: '#3a2a1a',
  k: '#2a2236', K: '#4a3a5a',
  r: '#c0394a', R: '#8a1f30',
  p: '#3d2c4a', P: '#1f1530', b: '#1a0f1a',
  m: '#6b3a1f', M: '#3d1f0f', e: '#f4d29a', y: '#fff6c0',
  W: '#ffffff', W2: '#fff0d8',
  o: '#ffd86b', O: '#c89236',
  t: '#7a5a3a', T: '#3a2a1a',
  d: '#000000',
  // Aurubis copper
  C: '#d28858', c: '#b56a3a', X: '#7a3e22', E: '#f4b888',
  // industrial steel
  N: '#6a6a78', n: '#3e3e4a', L: '#9098a8',
  // hi-vis
  V: '#ffe600', v: '#cc9a00', J: '#ff7700',
  // sparks / heat
  Y: '#fff89a', F: '#ff5a20', Z: '#ffaa55',
  // smoke
  u: '#888090', U: '#a8a0b0',
  // Aurubis CI
  A: '#0076A7',  // Aurubis blue (primary)
  a: '#005a82',  // Aurubis blue dark
  B: '#3aa0d2',  // Aurubis blue light
  // Rainbow (unicorn trail, mane)
  '1': '#ff5a7a',  // pink
  '2': '#ffaa3a',  // orange
  '3': '#ffe600',  // yellow
  '4': '#5acc5a',  // green
  '5': '#3aa0e0',  // blue
  '6': '#a060e0',  // purple
  '7': '#ffffff',  // white sparkle
};

function rasterize(rows, palette = PAL) {
  const cleaned = rows.replace(/^\n+|\n+$/g, '').split('\n');
  const w = Math.max(...cleaned.map(r => r.length));
  const h = cleaned.length;
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d');
  for (let y = 0; y < h; y++) {
    const row = cleaned[y];
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      if (ch === '.' || ch === ' ') continue;
      const color = palette[ch];
      if (!color) continue;
      ctx.fillStyle = color;
      ctx.fillRect(x, y, 1, 1);
    }
  }
  return canvas;
}

// === HERO (24x32) ===
const HERO_RUN_1 = `
........kkkkk...........
.......kKKKKKk..........
.......kKKKKKk..........
.......kssssk...........
.......ksdsdk...mmmM....
.......sssssk..mmemmM...
.......ssssss.mmeeemmM..
......rrrrrr.mmmeeemmm..
.....rrRrRrRr.mmmmmmm...
.....rrRRRRRrr.mTTm.....
.....rrRRRRRr...Tt......
......rrRRRr....Tt......
.......rrr......Tt......
.......ppp......Tt......
......pPpPp.....Tt......
......pPpPp.....Tt......
......pPpPp.....Tt......
......pP.Pp.....Tt......
......p..Pp.....Tt......
......p...p.....Tt......
......p...p.....Tt......
......b...b.....Tt......
......bb.bb.....Tt......
.....bbb.bbb....Tt......
....bbbb.bbbb...Tt......
................Tt......
................Tt......
................Tt......
................TT......
................tt......
................b.......
................b.......
`;

const HERO_RUN_2 = `
........kkkkk...........
.......kKKKKKk..........
.......kKKKKKk..........
.......kssssk...........
.......ksdsdk...mmmM....
.......sssssk..mmemmM...
.......ssssss.mmeeemmM..
......rrrrrr.mmmeeemmm..
.....rrRrRrRr.mmmmmmm...
.....rrRRRRRrr.mTTm.....
.....rrRRRRRr...Tt......
......rrRRRr....Tt......
.......rrr......Tt......
.......ppp......Tt......
.......pPp......Tt......
.......pPp......Tt......
......pPpP......Tt......
.....pPpPp......Tt......
.....pP.Pp......Tt......
.....p...p......Tt......
.....p...pp.....Tt......
.....b...bp.....Tt......
....bb..bbp.....Tt......
...bbb...bb.....Tt......
..bbbb...bbb....Tt......
................Tt......
................Tt......
................Tt......
................TT......
................tt......
................b.......
................b.......
`;

const HERO_JUMP = `
........kkkkk...........
.......kKKKKKk..........
.......kKKKKKk..........
.......kssssk...........
.......ksdsdk....mmmM...
.......sssssk...mmemmM..
.......sssssss.mmeeemmM.
......rrrrrrrrmmmeeemmm.
.....rrRrRrRr.mmmmmmm...
.....rrRRRRRrr.mTTm.....
.....rrRRRRRr...Tt......
......rrRRRr....Tt......
.......rrr......Tt......
.....pppppp.....Tt......
....pPpPpPpP....Tt......
....pPpPpPpP....Tt......
....pPpPpPpP....Tt......
.....pPpPpP.....Tt......
.....bbbbbb.....Tt......
....bbbb.bbb....Tt......
...bbbb...bb....Tt......
................Tt......
................Tt......
................Tt......
................Tt......
................Tt......
................Tt......
................Tt......
................TT......
................tt......
................b.......
................b.......
`;

const HERO_DUCK = `
.......kkkkk............
......kKKKKKk...........
......kKKKKKk....mmmM...
......kssssk....mmemmM..
......ksdsdk...mmeeemmM.
......sssssk..mmmeeemmm.
.....rrrrrrr...mmmmmmm..
....rrRrRrRrr...mTTm....
....rrRRRRRrrr...Tt.....
.....rrRRRRRr....Tt.....
......pppppp.....Tt.....
.....pPpPpPpP....Tt.....
....pPpPpPpPp....Tt.....
....pPpPpPpPp....Tt.....
....pPpPpPpPp....Tt.....
....pPpPpPpPp....Tt.....
....bbbbbbbbb....Tt.....
...bbbbb.bbbb....Tt.....
..bbbb....bbbb...Tt.....
.................Tt.....
.................Tt.....
.................Tt.....
.................TT.....
.................tt.....
.................b......
`;

const HERO_DEATH = `
.....mTTm...............
......Tt................
......Tt................
......Tt......kkkkkk....
......Tt.....kKKKKKKk...
......Tt....kssssss.k...
......Tt...kssdssdsk....
......Tt...kssssssk.....
......Tt..rrrrrrrrr.....
......Tt.rrRrRrRrRrr....
......Tt.rrRRRRRRRrr....
......Tt..rrrrrrrrr.....
......Tt....pppppp......
......Tt...pPpPpPpP.....
......Tt...pPpPpPpP.....
......Tt....bbbbbb......
......Tt....bbbbbb......
`;

const HORSE_STANDALONE = `
.....mmmM......
....mmmemM.....
...mmeeemmM....
..mmmeeemmm....
..mmeeeeemm....
..mmymmmmm.....
...mmTTmm......
....TtTt.......
....TtTt.......
....TtTt.......
....TtTt.......
....TtTt.......
....TtTt.......
....TtTt.......
....TtTt.......
`;

// === STAR (16x16) — replaces coin, golden 5-point star ===
const STAR = `
.......WW.......
.......oo.......
......o33o......
......oOOo......
.WWoooo33ooooWW.
.7oOOO3333OOOo7.
..o33333333333o.
...o3333333333o.
....o3333333OOo.
...oOO33333OOOo.
...oO33333333Oo.
..oO3333OOO333Oo
.oO33Oo7....oOOo
.oOO7..........7
................
................
`;

// === UNICORN (40x32) — for background fly-by, with rainbow mane/tail ===
const UNICORN = `
.....................33ooo.............
....................3oo3oo3............
...................3o3oo3oo3...........
....................3o3oo3.............
......................33................
.....1234567...........WWWWW............
....2WWWWWWWW1.........WWWWWW1..........
...3WWWWWWWWWW2.......WWWWWWWW2.........
..4WWWWWWWWWWWW3.....WWWWWWWWWW3........
.5WWWWWWWWWWWWWW4...WWWWWWWWWWWW4.......
.6WWWWWWWWWWWWWWW5.WWWWWWWWWWWWWW5......
..7WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW6....
...WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW...
....WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..
.....WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.
......WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.
.......WWWWWWWWWWWWWWWWWWWWWWWWWdWdWWWW.
........WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW..
.........WWWWWWWWWWWWWWWWWWWWWWWWWWWW...
..........WWWWWWWWWWWWWWWWWWWWWWWWWW....
...........WWWWWWWWWWWWWWWWWWWWWWWWWW...
............WWWWWWWWWWWWWWWWWWWWWWWWWW..
.............WWWWWWWWWWWWWWWWWWWWWWWWWW.
............W.W..W.W.W.W..W.W.W..W.W..WW
............W.W..W.W.W.W..W.W.W..W.W..W.
.............WW...WW...WW...WW...WW...W.
............W..W.W..W.W..W.W..W.W..W.W..
............W..W.W..W.W..W.W..W.W..W.W..
............WW...WW...WW...WW...WW...WW.
.........................................
.........................................
.........................................
`;

// === RAINBOW SPARKLE (8x8) — particle for unicorn trail ===
const SPARKLE = `
....7...
.7.737..
..7373..
7733373W
.737737.
..73737.
....7...
........
`;

// === STAR SPARKLE (small, 8x8) ===
const TINY_SPARKLE = `
...7....
..737...
.73737..
..737...
...7....
........
........
........
`;

// === COPPER INGOT STACK (32x14) — trimmed bottom ===
const COPPER_INGOT = `
......CCCCCCCCCCCCCCCCCC........
.....CEEEcccccccccccccCXX.......
.....CCCCCCCCCCCCCCCCCCXX.......
.....CcccccccccccccccccXX.......
....CCCCCCCCCCCCCCCCCCCCCXX.....
...CEEEccccccccccccccccccCXX....
...CCCCCCCCCCCCCCCCCCCCCCCCXX...
...CccccccccccccccccccccccCXX...
...CCCCCCCCCCCCCCCCCCCCCCCCXX...
...XXXXXXXXXXXXXXXXXXXXXXXXXn...
...nnnnnnnnnnnnnnnnnnnnnnnnnn...
`;

// === COPPER WIRE COIL (24x16) — trimmed ===
const WIRE_COIL = `
........CCCCCCCC........
.......CEcccccCC........
......CECCCCCCcCC.......
......CECccccCcCC.......
.....CECCCCCCCcCcC......
.....CECccccCcCccC......
.....CECCCCCCcCccC......
.....CECccccCcCccC......
......CECCCCCCcCC.......
......CEcccccccCC.......
.......CCCCCCCCC........
........XXXXXXX.........
........XXnnnXX.........
........XXXXXXX.........
........nnnnnn..........
`;

// === SLAG CHUNK (24x10) — glowing ember rocks, trimmed ===
const SLAG = `
.......nnnnnn...........
.....nnnFFnnnn..........
....nnFFFnFFnnn.........
...nnnFFFFFnFFnnn.......
...nnFFFnnnFFFnnnn......
...nnnFnnnnFnnnnnn......
....nnnnnnnnnnnnn.......
.....nnFFnnnnFnn........
......nFFnnnFnn.........
.......nnnnnn...........
`;

// === HANGING COPPER PIPE (40x12) — overhead, trimmed ===
const HANGING_PIPE = `
.....nnn........................nnn.....
....NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN....
...NNcccCCCCCCCCCCCCCCCCCCCCCCcccNNN....
...NNcCCEECEEEEEEEEEEEEEEEEEEECCcNNN....
...NNcCEcccccccccccccccccccccccENNN....
...NNcCccccccccccccccccccccccccCNNN....
...NNcCEcccccccccccccccccccccccENNN....
...NNcCCEECEEEEEEEEEEEEEEEEEEECCcNNN....
...NNcccCCCCCCCCCCCCCCCCCCCCCCcccNNN....
....NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN....
.....nnn........................nnn.....
.........................................
`;

// === ANODE PLATE (16x32) — tall narrow obstacle, trimmed ===
const ANODE_PLATE = `
.....nnn........
.....nNn........
....nNNNn.......
...CCCCCCCC.....
...CEcccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CECccCCC.....
...CECccccC.....
...CCCCCCCC.....
...nnnnnnnn.....
`;

// === HI-VIS WORKER (20x22) — trimmed ===
const HI_VIS_WORKER = `
.......VVVV.........
......VVVVVV........
......VsssV.........
......VsdsV.........
.......VsV..........
.......VVV..........
.......VVV..VV......
......VVVVVVVVV.....
.....VVvVVVvVVV.....
.....VVvVVVvVVV.....
.....VVVVVVVVVV.....
.....VvVvVvVvVV.....
......VVVvVVV.......
......nnnnnnn.......
......nNnNnNn.......
......nNnNnNn.......
......nNnNnNn.......
......nNnNnNn.......
......nnnnnnn.......
......bb...bb.......
.....bbb...bbb......
....bbbb...bbbb.....
`;

// === FORKLIFT (32x22) — trimmed ===
const FORKLIFT = `
.......nnn......................
......nNNn......................
......nNVn......................
......nVVn......................
......nVVnnnnnnnnnn.............
......nVVVVVVVVVVnn.............
......nVVssssVVVVnn.............
......nVVsdsVVVVVnn.............
......nVVssssVVVVnn.............
nnnn..nVVVVVVVVVVnn.............
nVVnnnVVVVVVVVVVnnnnnnnnnnn.....
nVVnnnVVVVVVVVVVnnVVVVVVVnn.....
nVVVVVVVVVVVVVVVVVVVVVVVVnn.....
nVVVVVVVVVVVVVVVVVVVVVVVVnn.....
nVVVVVVVVVVVVVVVVVVVVVVVVnn.....
nnnnnnnnnnnnnnnnnnnnnnnnnnn.....
.dddd...........dddd......nnn...
ddNNdd.........ddNNdd.....nNn...
dNNNNd.........dNNNNd.....nNn...
ddNNdd.........ddNNdd.....nnn...
.dddd...........dddd............
................................
`;

// === ELECTRIC ARC (20x14) — overhead, trimmed ===
const ARC_SPARK = `
....N....N....N.....
....N....N....N.....
....NN..NN....NN....
.....N..N......N....
......YY........Y...
.....YYYYY..YYYY....
....YZZZZYYZZZZY....
....YZFFZZFFZZZY....
.....ZFFFFFFFFZ.....
......YYYYYYY.......
.......YZZY.........
........YY..........
....................
....................
`;

// === SMOKESTACK (16x80) — trimmed ===
const SMOKESTACK = `
......uuuuu.....
.....uUuUuUu....
....uUUUUUUu....
.....uUuUuU.....
......uUUu......
......uuuu......
......NNNN......
.....NLLLLN.....
.....NLnnLN.....
.....NLLLLN.....
.....NLnnLN.....
.....NLLLLN.....
....nnnnnnnn....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
....NLLLLLLN....
....NLnnnnLN....
...NNNNNNNNNN...
`;

// === REFINERY TOWER (32x80) — trimmed ===
const REFINERY_TOWER = `
............nnnn................
...........nNLLNn...............
...........nLLLLn...............
...........nLnnLn...............
...........nLLLLn...............
...........nLLLLn..nnnnn........
...........nLLLLn.nNLLLn........
...........nLLLLn.nLLLLn........
...........nLLLLn.nLnnLn........
......nnnnnnnnnnn.nLLLLn........
......nNLLLLLLLLLnnnnnnn........
......nLLnnnnnnLLLLLLLLLn.......
......nLLLLLLLLLLLnnnnLLn.......
......nLnnnnnnnnLLLLLLLLn.......
......nLLLLLLLLLLLnnnnLLn.......
......nLnnnnnnnnLLLLLLLLn.......
.nnnnnnnnnnnnnnnnnnnnnnnnnnnnn..
.nNLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLLnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nLnnnnnnnnnnnnnnnnnnnnnnnnnLn..
.nLLLLLLLLLLLLLLLLLLLLLLLLLLLn..
.nnnnnnnnnnnnnnnnnnnnnnnnnnnnn..
`;

// === AURUBIS BILLBOARD (64x40) — blue triangle logo + AURUBIS text ===
const AURUBIS_BILLBOARD = `
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
nLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLn
nLWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWWWWWWAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWWWWWAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWWWWAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWWWAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWWAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWAAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWAAAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWAAAAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWAAAAAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWAAAAAAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWAAAAAAAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWAAAAAAAAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWAAAAWWAAWWWAWWWWAAAWWAAAAWWWAAAAAWWAAAWWAAAWWWWWWWWWn
nLWWWWWWWWWAAAAAAWAAWWAAWWWAAAAAWAAAAAWWAAAAAWAAAAAWAAAAAWWWWWWWn
nLWWWWWWWWWAWWWWAWAAWAAAWWWAWWWAWAWWWAWWAWWWWWAWWWAWAWWWAWWWWWWWn
nLWWWWWWWWWAAAAAAWAAAAWAAWWAAAAAWAAAAWWWAAAAAWAAAAAWAAAAAWWWWWWWn
nLWWWWWWWWWAWWWAWWAAAWAAWWWAWWWAWAWWAWWWWWWWAWAWWWAWAWWWAWWWWWWWn
nLWWWWWWWWWAWWWAWWAAWWAAWWWAWWWAWAWWWAWWAAAAAWAWWWAWAAAAAWWWWWWWn
nLWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWMETALS FOR PROGRESSWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWn
nLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLn
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
....nn..............................................nn..........
....nn..............................................nn..........
....nn..............................................nn..........
....nn..............................................nn..........
....nn..............................................nn..........
....nn..............................................nn..........
....nn..............................................nn..........
...nnnn............................................nnnn.........
`;

// === AURUBIS CRATE — copper-shipping crate, ground obstacle (28x18) ===
const AURUBIS_CRATE = `
............................
...nnnnnnnnnnnnnnnnnnnnnn...
...nXXXXXXXXXXXXXXXXXXXXn...
...nXAAAAAAAAAAAAAAAAAAXn...
...nXAcccccccccccccccAAXn...
...nXAcCCCCCCCCCCCCcAAAXn...
...nXAcCAURUBIScCcAAAAAXn...
...nXAcCCCCCCCCCCCCcAAAXn...
...nXAcccccccccccccccAAXn...
...nXAAAAAAAAAAAAAAAAAAXn...
...nXAAcAAcAAcAAcAAcAAAXn...
...nXAAAAAAAAAAAAAAAAAAXn...
...nXXXXXXXXXXXXXXXXXXXXn...
...nnnnnnnnnnnnnnnnnnnnnn...
....nn..............nn......
....nn..............nn......
....nn..............nn......
....nnnn..........nnnn......
`;

// === CABLE SPOOL (28x28) — TALL spool of copper cable, hard to jump ===
const CABLE_SPOOL = `
............................
............................
.......nnnnnnnnnnnnn........
......nLLLLLLLLLLLLLLn......
.....nLnnnnnnnnnnnnnnLn.....
.....nLnCCCCCCCCCCCnnLn.....
.....nLnCcccccccccnLnLn.....
.....nLnCcEEEEcccnLnnLn.....
....nnLnCcECCCCccnLnnLn.....
....nLLnCcECccccnLLLnLn.....
....nLLnCcECccccnLLLnLn.....
....nLLnCcECCCCccnLLnLn.....
....nLLnCcEEEcccccnLnLn.....
....nLLnCcccccccccnLnLn.....
....nLLnCccccccccnLLnLn.....
.....nLnCCCCCCCCCnLLnLn.....
.....nLnnnnnnnnnnLLnnLn.....
.....nLLLLLLLLLLLLLLnLn.....
.....nLnnnnnnnnnnnnnLLn.....
.....nLnCCCCCCCCCCCCnLn.....
.....nLnCCCCCCCCCCCCnLn.....
.....nLLLLLLLLLLLLLLLLn.....
....nnLLLLLLLLLLLLLLnLn.....
...nnLnnnnnnnnnnnnnnnLnn....
...nLnnnnnnnnnnnnnnnnnLn....
...nLn..............nnnLn...
...nnnn............nn..nn...
............................
`;

// === CHEMICAL DRUM (16x22) — yellow hazard barrel ===
const CHEMICAL_DRUM = `
....nnnnnnnnn...
...nVVVVVVVVVn..
..nVdJVVVVVdJVn.
..nVJJVVVVVJJVn.
..nVVVVVVVVVVVn.
..nVVVdddddVVVn.
..nVdddddVVdVdn.
..nVdVdVdVVdVdn.
..nVdddddVVdVdn.
..nVdVdVdVVdddn.
..nVVVVVVVVVVVn.
..nVVVdJdVVVVVn.
..nVdddJddJdJdn.
..nVdJdJdJdJdJn.
..nVdddJddJdJdn.
..nVVVVVVVVVVVn.
..nVdJVVVVVdJVn.
..nVJJVVVVVJJVn.
..nVVVVVVVVVVVn.
...nnnnnnnnnnn..
...nnnnnnnnnnn..
....nnnnnnnnn...
`;

// === COPPER SHEET (8x36) — vertical thin obstacle ===
const COPPER_SHEET = `
nnnnnnnn
nXAAAAXn
nXcCCcXn
nXcEcEcn
nXccCCcn
nXcCccXn
nXcEcEXn
nXccCcXn
nXcCcCXn
nXcEcEXn
nXccCcXn
nXcCccXn
nXcEcEXn
nXccCcXn
nXcCcCXn
nXcEcEXn
nXccCcXn
nXcCccXn
nXcEcEXn
nXccCcXn
nXcCcCXn
nXcEcEXn
nXccCcXn
nXcCccXn
nXcEcEXn
nXccCcXn
nXcCcCXn
nXcEcEXn
nXccCcXn
nXcCccXn
nXcEcEXn
nXccCcXn
nXcCcCXn
nXAAAAXn
nXXXXXXn
nnnnnnnn
`;

// === STEAM VENT (24x18) — overhead steam jet, must duck ===
const STEAM_VENT = `
....uuuuuuuuuuuuuuuu....
...uUUUUUUUUUUUUUUUUu...
..uUUUUUUuuUUuuUUUUUUu..
..uUUUuUUUUuUUUUuUUUUu..
..uuUUuuUUUUUUuUuuUUuu..
....uuuuuuuuuuuuuuuu....
.....uuuuuuuuuuuuuu.....
.....nnnnnnnnnnnnnn.....
.....nLLLLLLLLLLLLn.....
.....nLnnnnnnnnnnLn.....
.....nLnLLLLLLLLnLn.....
.....nLLLLLLLLLLLLn.....
.....nnnnnnnnnnnnnn.....
......nnnnnnnnnnnn......
.......nnnnnnnnnn.......
........................
........................
........................
`;

// === DRONE (14x14) ===
const DRONE = `
..k.......k...
..k.......k...
..kk.....kk...
..ddkkkkkdd...
.dKKKKKKKKKd..
.dKKddKddKKd..
.dKKKKWKKKKd..
.dKKKddKKKKd..
.dKKKKKKKKKd..
..ddddddddd...
.....dd.......
....d..d......
....k..k......
....kkkk......
`;

// === CLOUD (smoke) ===
const CLOUD = `
....uuuUUUUu....
...uUUUUUUUUU...
..uUUUUUUUUUUu..
.uUUUUUUUUUUUUu.
.UUUUUUUUUUUUUU.
.uUUUUUUUUUUUUu.
..uUUUUUUUUUUu..
...uUUUUUUUUu...
`;

// === SCRAP PILE ===
const SCRAP_PILE = `
....nnNnnNn.....
...nnNcNNcNn....
..nnNcNcNcNNn...
.nnNcNcccNcNn...
.nNcNcNNcNcNn...
.nNNNNNcNNNNn...
..nnnnnnnnnn....
...nnnnnnnn.....
`;

// === SIGNAL TOWER ===
const SIGNAL_TOWER = `
.....nnn.......
.....nLn.......
.....nLn.......
....nnLnn......
...nFnLnYn.....
...nFnLnYn.....
....nnLnn......
.....nLn.......
.....nLn.......
.....nLn.......
.....nLn.......
.....nLn.......
.....nLn.......
.....NNN.......
....NNNNN......
`;

// === HELGA ===
const HELGA = `
................hhhhhhhh........................................
.............hhhhhhhhhhhhhh.....................................
............hhhhhhhhhhhhhhhh....................................
...........hhhhhhhhhhhhhhhhhh...................................
...........hhhhhhsssssshhhhhh...................................
...........hhhhssssssssssshhh...................................
...........hhssssssssssssssh....................................
...........hsssssssssssssss.....................................
...........hsssdssssssdsssss....................................
...........hsssdssssssdsssss....................................
...........hsssssWsWssssssss....................................
...........hsssssssssssssssss...................................
...........hsssssddssssssssss...................................
...........hssssssWWssssssssss..................................
...........hsssssssssssssssss...................................
.............hssssssssssssh.....................................
..............hhhhssshhhhh......................................
..............rrrrrrrrrrrr......................................
............rrrrRrRrRrRrRrr.....................................
...........rrRRRRRRRRRRRRRrr....................................
..........rrRRRRRRRRRRRRRRRrr...................................
.........rrRRRRRRRRRRRRRRRRRrr..................................
.........rrRRRRRRRRRRRRRRRRRrr..................................
.........rrRRRRRRRRRRRRRRRRRrr..................................
`;

// === POWER-UP ICONS (kept simple) ===
const POWERUP_TURBO = `
....FFFF........
...FYYFFY.......
..FYYZZFFY......
.FYZZZZZFY......
.FZZZZZZZF......
..FZZZZZZF......
...FZZZZF.......
....FFFF........
`;

const POWERUP_MAGNET = `
....FFFFFFFF....
...FFcccccCC....
...FCcccccCC....
...FC...CCC.....
...FC...CCC.....
...FCcccccCC....
...FCcccccCC....
...FCcccccCC....
................
`;

const POWERUP_SHIELD = `
......LLLL.......
.....LCCCCL......
....LCcccccL.....
....LCcEEcCL.....
....LCcEEcCL.....
....LCcccccL.....
.....LcccccL.....
......LcccL......
.......LcL.......
........L........
`;

const SPRITES = {
  hero_run_1: HERO_RUN_1,
  hero_run_2: HERO_RUN_2,
  hero_jump: HERO_JUMP,
  hero_duck: HERO_DUCK,
  hero_death: HERO_DEATH,
  horse_standalone: HORSE_STANDALONE,
  star: STAR,
  unicorn: UNICORN,
  sparkle: SPARKLE,
  tiny_sparkle: TINY_SPARKLE,
  copper_ingot: COPPER_INGOT,
  wire_coil: WIRE_COIL,
  slag: SLAG,
  hanging_pipe: HANGING_PIPE,
  anode_plate: ANODE_PLATE,
  hi_vis_worker: HI_VIS_WORKER,
  forklift: FORKLIFT,
  arc_spark: ARC_SPARK,
  drone: DRONE,
  aurubis_billboard: AURUBIS_BILLBOARD,
  aurubis_crate: AURUBIS_CRATE,
  cable_spool: CABLE_SPOOL,
  chemical_drum: CHEMICAL_DRUM,
  copper_sheet: COPPER_SHEET,
  steam_vent: STEAM_VENT,
  cloud: CLOUD,
  scrap_pile: SCRAP_PILE,
  signal_tower: SIGNAL_TOWER,
  smokestack: SMOKESTACK,
  refinery_tower: REFINERY_TOWER,
  helga: HELGA,
  pu_turbo: POWERUP_TURBO,
  pu_magnet: POWERUP_MAGNET,
  pu_shield: POWERUP_SHIELD,
};

export function makeRect(scene, key, w, h, color) {
  if (scene.textures.exists(key)) return;
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  const ctx = c.getContext('2d');
  ctx.fillStyle = color;
  ctx.fillRect(0, 0, w, h);
  scene.textures.addCanvas(key, c);
}

export function makeSky(scene, key, w, h, top, bottom) {
  if (scene.textures.exists(key)) return;
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  const ctx = c.getContext('2d');
  const grd = ctx.createLinearGradient(0, 0, 0, h);
  grd.addColorStop(0, top);
  grd.addColorStop(1, bottom);
  ctx.fillStyle = grd;
  ctx.fillRect(0, 0, w, h);
  scene.textures.addCanvas(key, c);
}

export function makeGround(scene, key, w, h, soil, grass, accent) {
  if (scene.textures.exists(key)) return;
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  const ctx = c.getContext('2d');
  ctx.fillStyle = soil;
  ctx.fillRect(0, 0, w, h);
  // metal plate edge
  ctx.fillStyle = grass;
  ctx.fillRect(0, 0, w, 3);
  ctx.fillStyle = accent;
  for (let i = 0; i < w; i += 4) {
    ctx.fillRect(i, 1, 1, 1);
    ctx.fillRect(i + 2, 2, 1, 1);
  }
  ctx.fillStyle = '#000';
  ctx.globalAlpha = 0.22;
  for (let i = 0; i < 40; i++) {
    const x = Math.floor(Math.random() * w);
    const y = 4 + Math.floor(Math.random() * (h - 4));
    ctx.fillRect(x, y, 1, 1);
  }
  ctx.fillStyle = '#b56a3a';
  ctx.globalAlpha = 0.4;
  for (let i = 0; i < 12; i++) {
    const x = Math.floor(Math.random() * w);
    const y = 5 + Math.floor(Math.random() * (h - 5));
    ctx.fillRect(x, y, 1, 1);
  }
  // Aurubis blue accent stripe (subtle)
  ctx.fillStyle = '#0076A7';
  ctx.globalAlpha = 0.5;
  for (let i = 0; i < 4; i++) {
    const x = Math.floor(Math.random() * w);
    const y = 4 + Math.floor(Math.random() * (h - 4));
    ctx.fillRect(x, y, 2, 1);
  }
  ctx.globalAlpha = 1;
  scene.textures.addCanvas(key, c);
}

export function registerSprites(scene) {
  Object.entries(SPRITES).forEach(([key, str]) => {
    if (scene.textures.exists(key)) return;
    const canvas = rasterize(str);
    scene.textures.addCanvas(key, canvas);
  });
}

export { PAL };
